service: gmap
runtime: nodejs12
env: standard
env_variables:
  DBHOST: "<dbhost>"
  DBNAME: "<dbname>"
  DBUSER: "<dbuser>"
  DBPASSWORD: "<dbpassword>"
  DBENGINE: "postgresql"
  APPLICATION_NAME : "GMAP"
  APPLICATION_TITLE : "GMAP"
  APPLICATION_PORT : "8080"
  PROJECT : "dvt-apac-playground-3"

